language: node_js
node_js:
- "12.18.0"

script:
  - npm test
before_install:
  - cd STAT-server

env:
  global:
  - secure: K2/m9gQn2CmzvHNhAUOAIAM+ozu1NLU2OkELg8QQ35Q0+IRDRyDYZFcV6InEAMK0WuUIi2a7l/WtwLUZhP2o6j8KZGbFWKfO7/Uu5seQdh+C74X7/8Rb94RUqIt5xAAr3u660OybaLJrf1q7Sz7G6OONyR/qnZ6iKxhdkf0ett/THPYwgXm6arLu/Gxd4ng63vGmrf7mikhFOw7PfsZTHaJoz/zUDfJJQV8/TrseEwjVKrwkZvEIVxeXHybXL0rmF2YwXWRzzz0wLm1ddKTBP/ghwGoGWnmf9NRD4Gq0yWPBoswpHgfexfUYtHv8A9I239XCDlFR1zBdTrFDH/AUm9qgAkwrCjanPxTIoeEhnHkeU40RnHb/uIVOrqdGDgx+BitRmX2oYyh6xGl/S3Y3fIhiZ0TvxiEXTb6R6LamtKeIXOYyGaHtPZA8d59oQK2lcXrzrPva+wSVe1VRVTDq6c6lDUVmOngdyVHJpyxS0GMp3es2Gd5rzxCNRf9cdy61DDjPDrCKyZ5j7Jl54wPssxMODT16OR3+NV5coO+NVjO7EQFZP90ozbDbi2FEOXNoN0ReAegYzcsYcoXOFKvxz50ck/HC+lZdvnFYAwTg4LGsG6lYpeAKJf70tN34chaEGQXUYHFVDQFffOsnu0XV2maOBl3iCfTzs0Bng+BZYAA=
  - secure: wD3xeWkWKhVTUPjvADQ1BKdBzRNuoGRzs8liSCKyrVVnbgd2qLBOuCeyUAS87a4+nTDIGhkgrzviS9f1TXHmpDdCUY/3MW8AjmdOpZthH515ZT5SAz/ebrNeA0chFXL8ZqBgX9WkCQlt1S5KLTZsApUFmQq7vtEXSCAOYe+4j5Rf5hFWAoS3Alkpfqwzy69a2RXsjYVuHig7dfUxAHAThpIcQNisbnR6dYTbTfciey+sFxMXadR+1zeIyrofFGN86y0IZJ0mwGZiN+zrVL1xYLWOYltetYz5bxrjZV96S68dwpTXVOh8Nv6nzwe0gCUiY4Q0ZQl+nhr1/buFFBWlorgljSS4TU7K4qv5Wstpt+8m8tTnnEoLRWEd6fTGqnR74tHCqrAeCE12J5CSCssJrjyiJQy/zBo2Twz7QhL3su1ocrw1MRPBEC9Q+X+tfwWS0h1U2g//4Gwg+FeWUSX59kvpTkXeO6HHgN1PuexALC8k+xVkDrLCRW2vZwJE8Wl89h6pDCIGOWFIPztFJADWI2XdAPX2KT0BnMPY1MiQpjECie2HpKe96qgysdYPT2zvsEgRA3TZwl8dpjG8QGzXJQxq3DoaH4MjBGHX3SjU/mNB3KU3r+xLkvsnpBxMOwgo/7ZPYhEWgzM1UkKzNIjc7745+CII/bm98QPppSicMl4=
  
