name: Build
on:
  push:
    branches: [ testing-CICD ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: STAT
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install
            npm start
